In [2]:
print("uv 활성화 완료")

uv 활성화 완료


In [3]:
import torch

In [3]:
torch.cuda.is_available()

True

In [36]:
# cuda 이용하여 텐서 생성
x = torch.tensor([1.0, 2.0, 3.0], device="cuda")
print(x)
print(x.device)

tensor([1., 2., 3.], device='cuda:0')
cuda:0


In [11]:
# 파이토치 버전 확인
print(torch.__version__)

2.10.0+cu126


In [14]:
import numpy as np
np_data = np.array([[1,2], [3,4]])
torch.tensor(np_data)

tensor([[1, 2],
        [3, 4]])

In [15]:
torch.from_numpy(np_data)

tensor([[1, 2],
        [3, 4]])

In [19]:
torch.arange(1, 10, 2)

tensor([1, 3, 5, 7, 9])

In [21]:
torch.linspace(0, 10, 100)

tensor([ 0.0000,  0.1010,  0.2020,  0.3030,  0.4040,  0.5051,  0.6061,  0.7071,
         0.8081,  0.9091,  1.0101,  1.1111,  1.2121,  1.3131,  1.4141,  1.5152,
         1.6162,  1.7172,  1.8182,  1.9192,  2.0202,  2.1212,  2.2222,  2.3232,
         2.4242,  2.5253,  2.6263,  2.7273,  2.8283,  2.9293,  3.0303,  3.1313,
         3.2323,  3.3333,  3.4343,  3.5354,  3.6364,  3.7374,  3.8384,  3.9394,
         4.0404,  4.1414,  4.2424,  4.3434,  4.4444,  4.5455,  4.6465,  4.7475,
         4.8485,  4.9495,  5.0505,  5.1515,  5.2525,  5.3535,  5.4545,  5.5556,
         5.6566,  5.7576,  5.8586,  5.9596,  6.0606,  6.1616,  6.2626,  6.3636,
         6.4646,  6.5657,  6.6667,  6.7677,  6.8687,  6.9697,  7.0707,  7.1717,
         7.2727,  7.3737,  7.4747,  7.5758,  7.6768,  7.7778,  7.8788,  7.9798,
         8.0808,  8.1818,  8.2828,  8.3838,  8.4848,  8.5859,  8.6869,  8.7879,
         8.8889,  8.9899,  9.0909,  9.1919,  9.2929,  9.3939,  9.4949,  9.5960,
         9.6970,  9.7980,  9.8990, 10.00

In [31]:
torch.randint(0, 255, (3, 4))

tensor([[154, 110, 193,  40],
        [114,  88,  37, 219],
        [148, 106, 103, 120]])

In [ ]:
torch.zeros((3, 4)) # 0으로 채워진 텐서 생성

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
torch.ones((3, 4)) # 1로 채워진 텐서 생성

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
torch.full((3, 4), 255) # 255로 채워진 텐서 생성

tensor([[255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255]])

In [29]:
torch.eye(5,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 0.]])

In [35]:
# tensor의 속성 확인
tdata = torch.randint(0, 255, (128, 128))
print(tdata.shape) # 텐서의 형태
print(tdata.dtype) # 텐서의 데이터 타입
print(tdata.device) # 텐서가 위치한 디바이스


torch.Size([128, 128])
torch.int64
cpu


In [37]:
tdata.T

tensor([[167, 103, 103,  ..., 228, 105,  58],
        [ 57,  73, 126,  ..., 135, 232,   2],
        [170, 235, 210,  ...,  92,  46, 102],
        ...,
        [ 11, 205, 168,  ..., 188,  97,  72],
        [ 91, 157, 169,  ..., 228, 254, 227],
        [231, 141, 204,  ...,   6, 188,  24]])

In [38]:
tdata.to("cuda") # 텐서를 cuda로 이동

tensor([[167,  57, 170,  ...,  11,  91, 231],
        [103,  73, 235,  ..., 205, 157, 141],
        [103, 126, 210,  ..., 168, 169, 204],
        ...,
        [228, 135,  92,  ..., 188, 228,   6],
        [105, 232,  46,  ...,  97, 254, 188],
        [ 58,   2, 102,  ...,  72, 227,  24]], device='cuda:0')

In [40]:
tdata = torch.zeros(2,3)
tdata

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [41]:
tdata + 10

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [42]:
tdata = torch.zeros(2,3)
tdata1 = torch.ones(2,3)
tdata + tdata1

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [43]:
mat1 = torch.tensor([[1,2,3], [4,5,6]])
mat2 = torch.tensor([[7,8], [9,10], [11,12]])
torch.matmul(mat1, mat2)

tensor([[ 58,  64],
        [139, 154]])

In [48]:
data = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
data

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [49]:
data[0] # 첫 번째 행

tensor([1, 2, 3])

In [50]:
data[:, 0] # 첫 번째 열

tensor([1, 4, 7])

In [52]:
data[:, 0:2] # 0, 2 번째 열

tensor([[1, 2],
        [4, 5],
        [7, 8]])

In [ ]:

# 행렬 확인
tdata.shape

In [ ]:
# 128*128 크기의 텐서를 64*64 크기의 텐서로 변환
tdata = torch.ones(128, 128)

In [63]:
data = torch.tensor([[1, 2], [3, 4]])
print(data)

tensor([[1, 2],
        [3, 4]])


In [77]:
dat = torch.sum(data).item() # 텐서의 모든 원소의 합을 스칼라 값으로 반환
print(dat)

# int 를 float로 변환
dat_float = float(dat)
print(dat_float)

10
10.0


In [78]:
dat = torch.randint(0, 255, (128, 128))
print(dat)

tensor([[166,  29,  14,  ...,  54, 193, 250],
        [205, 208,  76,  ...,  68, 240, 221],
        [ 44, 211, 236,  ..., 235, 165,  72],
        ...,
        [218, 103, 210,  ...,  83, 171, 223],
        [125, 250, 219,  ..., 131, 174,  65],
        [114,  73,  69,  ...,  32, 243, 175]])


In [81]:
# numpy 배열로 변환
dat_numpy = dat.numpy()
dat_numpy

array([[166,  29,  14, ...,  54, 193, 250],
       [205, 208,  76, ...,  68, 240, 221],
       [ 44, 211, 236, ..., 235, 165,  72],
       ...,
       [218, 103, 210, ...,  83, 171, 223],
       [125, 250, 219, ..., 131, 174,  65],
       [114,  73,  69, ...,  32, 243, 175]], shape=(128, 128))

In [83]:
# numpy 배열을 다시 텐서로 변환
torch.tensor(dat_numpy)

tensor([[166,  29,  14,  ...,  54, 193, 250],
        [205, 208,  76,  ...,  68, 240, 221],
        [ 44, 211, 236,  ..., 235, 165,  72],
        ...,
        [218, 103, 210,  ...,  83, 171, 223],
        [125, 250, 219,  ..., 131, 174,  65],
        [114,  73,  69,  ...,  32, 243, 175]])

In [85]:
data = torch.tensor([1, 2, 3])
data.shape

torch.Size([3])

In [87]:
data_mat = data.unsqueeze(0) # 1차원 텐서를 2차원 텐서로 변환
data_mat.shape

torch.Size([1, 3])

In [89]:
data.squeeze(0) # 2차원 텐서를 1차원 텐서로 변환
data.shape

torch.Size([3])

In [95]:
data = torch.tensor([[1, 2], [3, 4]])
data.dim() # 텐서의 차원 수 확인
data.view(-1) # 텐서를 1차원으로 변환

tensor([1, 2, 3, 4])

In [2]:
torch.cuda.is_available()


True

In [3]:
torch.cuda.device_count()

1

In [1]:
print("hello")

hello


In [2]:
import time
import torch

def print_device_info():
    print("========== Device Info ==========")
    print(f"PyTorch version : {torch.__version__}")
    print(f"CUDA available  : {torch.cuda.is_available()}")

    if not torch.cuda.is_available():
        return

    device_idx = torch.cuda.current_device()
    props = torch.cuda.get_device_properties(device_idx)

    print(f"Using device    : cuda:{device_idx}")
    print(f"Device name     : {props.name}")
    print(f"Compute capability : {props.major}.{props.minor}")
    print(f"Total VRAM      : {props.total_memory / (1024**3):.2f} GB")
    print(f"CUDA version    : {torch.version.cuda}")
    print("=================================\n")


@torch.no_grad()
def gpu_burn_exact(seconds=10.0,
                   dtype=torch.float16,
                   size=8192,
                   use_relu=True):

    if not torch.cuda.is_available():
        raise RuntimeError("CUDA를 사용할 수 없습니다.")

    device = torch.device("cuda")

    torch.backends.cuda.matmul.allow_tf32 = True
    torch.set_float32_matmul_precision("high")

    print_device_info()
    print(f"Matrix size     : {size} x {size}")
    print(f"Dtype           : {dtype}")
    print(f"Burn time       : {seconds:.2f} seconds")
    print(f"Extra op        : {'relu' if use_relu else 'none'}\n")

    a = torch.randn((size, size), device=device, dtype=dtype)
    b = torch.randn((size, size), device=device, dtype=dtype)

    # 워밍업
    c = a @ b
    if use_relu:
        c.relu_()
    torch.cuda.synchronize()

    start = time.perf_counter()
    total_matmuls = 0

    while True:
        c = a @ b
        if use_relu:
            c.relu_()

        torch.cuda.synchronize()
        total_matmuls += 1

        if time.perf_counter() - start >= seconds:
            break

    total_time = time.perf_counter() - start

    # -------------------------
    # FLOPs 계산
    # -------------------------

    matmul_flops = 2 * (size ** 3)

    relu_flops = size ** 2 if use_relu else 0

    flops_per_iter = matmul_flops + relu_flops

    total_flops = flops_per_iter * total_matmuls

    print("\n========== Summary ==========")
    print(f"Total time          : {total_time:.3f} sec")
    print(f"Total matmuls       : {total_matmuls}")
    print(f"FLOPs per matmul    : {matmul_flops / 1e12:.3f} TFLOPs")
    if use_relu:
        print(f"ReLU FLOPs per iter : {relu_flops / 1e9:.3f} GFLOPs")

    print(f"--------------------------------")
    print(f"Total FLOPs         : {total_flops / 1e12:.3f} TFLOPs")
    print(f"Achieved TFLOPS     : {(total_flops / total_time) / 1e12:.3f}")
    print("=============================")


if __name__ == "__main__":
    gpu_burn_exact(
        seconds=10.0,
        dtype=torch.float16,
        size=8192,
        use_relu=True
    )

========== Device Info ==========
PyTorch version : 2.10.0+cu126
CUDA available  : True
Using device    : cuda:0
Device name     : NVIDIA GeForce RTX 4070 Laptop GPU
Compute capability : 8.9
Total VRAM      : 8.00 GB
CUDA version    : 12.6

Matrix size     : 8192 x 8192
Dtype           : torch.float16
Burn time       : 10.00 seconds
Extra op        : relu


========== Summary ==========
Total time          : 10.034 sec
Total matmuls       : 232
FLOPs per matmul    : 1.100 TFLOPs
ReLU FLOPs per iter : 0.067 GFLOPs
--------------------------------
Total FLOPs         : 255.102 TFLOPs
Achieved TFLOPS     : 25.425


In [3]:
import os
import time
import torch


def print_cpu_info():
    print("========== CPU Info ==========")
    print(f"PyTorch version : {torch.__version__}")
    print(f"Using device    : cpu")
    print(f"Intra-op threads: {torch.get_num_threads()}")
    print(f"Inter-op threads: {torch.get_num_interop_threads()}")

    for k in ["OMP_NUM_THREADS", "MKL_NUM_THREADS", "OPENBLAS_NUM_THREADS"]:
        if k in os.environ:
            print(f"{k} = {os.environ[k]}")
    print("================================\n")


@torch.no_grad()
def cpu_burn_exact(seconds=10.0,
                   dtype=torch.float32,
                   size=2048,
                   intraop_threads=None,
                   use_relu=True):
    """
    CPU에서 정확히 seconds 동안 matmul 반복 수행.
    종료 후 총 FLOPs 및 평균 GFLOPS 출력.
    """

    if intraop_threads is not None:
        torch.set_num_threads(int(intraop_threads))

    print_cpu_info()
    print(f"Matrix size     : {size} x {size}")
    print(f"Dtype           : {dtype}")
    print(f"Burn time       : {seconds:.2f} seconds")
    print(f"Extra op        : {'relu' if use_relu else 'none'}\n")

    device = torch.device("cpu")

    a = torch.randn((size, size), device=device, dtype=dtype)
    b = torch.randn((size, size), device=device, dtype=dtype)

    # 워밍업
    c = a @ b
    if use_relu:
        c.relu_()

    start = time.perf_counter()
    total_matmuls = 0

    while True:
        c = a @ b
        if use_relu:
            c.relu_()

        total_matmuls += 1

        if time.perf_counter() - start >= seconds:
            break

    total_time = time.perf_counter() - start

    # -------------------------
    # FLOPs 계산
    # -------------------------

    matmul_flops = 2 * (size ** 3)
    relu_flops = size ** 2 if use_relu else 0
    flops_per_iter = matmul_flops + relu_flops
    total_flops = flops_per_iter * total_matmuls

    print("\n========== Summary ==========")
    print(f"Total time          : {total_time:.3f} sec")
    print(f"Total matmuls       : {total_matmuls}")
    print(f"FLOPs per matmul    : {matmul_flops / 1e9:.3f} GFLOPs")
    if use_relu:
        print(f"ReLU FLOPs per iter : {relu_flops / 1e9:.3f} GFLOPs")

    print(f"--------------------------------")
    print(f"Total FLOPs         : {total_flops / 1e12:.3f} TFLOPs")
    print(f"Achieved GFLOPS     : {(total_flops / total_time) / 1e9:.3f}")
    print("=============================")


if __name__ == "__main__":
    cpu_burn_exact(
        seconds=10.0,
        dtype=torch.float32,
        size=2048,
        intraop_threads=None,  # 예: 8로 고정하고 싶으면 8
        use_relu=True
    )
    

========== CPU Info ==========
PyTorch version : 2.10.0+cu126
Using device    : cpu
Intra-op threads: 16
Inter-op threads: 16

Matrix size     : 2048 x 2048
Dtype           : torch.float32
Burn time       : 10.00 seconds
Extra op        : relu


========== Summary ==========
Total time          : 10.018 sec
Total matmuls       : 361
FLOPs per matmul    : 17.180 GFLOPs
ReLU FLOPs per iter : 0.004 GFLOPs
--------------------------------
Total FLOPs         : 6.203 TFLOPs
Achieved GFLOPS     : 619.216
